# Generated by Django 4.2.7 on 2026-06-11 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('safety', '0004_routehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sosdeliverylog',
            options={},
        ),
        migrations.RemoveField(
            model_name='sosdeliverylog',
            name='created_at',
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_alerts', models.BooleanField(default=True)),
                ('location_updates', models.BooleanField(default=True)),
                ('community_reports', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('show_ai_recommendations', models.BooleanField(default=True)),
                ('show_analytics', models.BooleanField(default=True)),
                ('show_heatmap', models.BooleanField(default=True)),
                ('show_quick_access', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=20)),
                ('auto_theme', models.BooleanField(default=False)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('data_privacy', models.BooleanField(default=True)),
                ('session_timeout', models.IntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
